### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [khrapalOK/grid__template__khrapal#1]
1)
Внешний вид не соответствует поставленной задаче.
Сравните результат с макетом или мастер шаблоном.
![image](https://user-images.githubusercontent.com/8464662/197357190-731b46f9-99d7-4606-93d9-749e4980fa69.png)

2)

Модификатор не может использоваться без класса блока или класса элемента, это нарушает основные концепции БЭМ.
Подробная информация представлена в презентации урока или в записи трансляции (дополнительная ссылка к уроку в документации курса).
Справочник https://ru.bem.info/methodology/quick-start/

![image](https://user-images.githubusercontent.com/8464662/197357249-724ff112-fba4-46b2-95da-3a8a049fbbc0.png)

3)

Не спамьте код "мусорными" пустыми строками.
Одной строки в качестве разделителя - более чем достаточно.
Две и более пустых строки - спам, который следует удалить из кода.

![image](https://user-images.githubusercontent.com/8464662/197357467-7678835f-ee80-403b-a5f8-4adce03355fb.png)

**Comment by Alecto** [comment]
2 - не исправлено
![image](https://user-images.githubusercontent.com/8464662/197393571-990e5ec3-dac9-43f0-97d8-0eb4392d3ae6.png)


4)

Элемент - всегда часть блока, а не другого элемента.
Это означает, что в названии элементов нельзя прописывать иерархию вида block__elem1__elem2.
Справочник https://ru.bem.info/methodology/quick-start/

![image](https://user-images.githubusercontent.com/8464662/197393585-98dde82b-5318-4812-839a-9fc68934f75e.png)

**Comment by khrapalOK** [comment]
исправил, понял что Вы имели в виду
надеюсь теперь правильно.


вс, 23 окт. 2022 г. в 16:00, Andrii Fomenko ***@***.***>:

**Comment by khrapalOK** [comment]
забыл ввложить ссылку на шаблон
https://khrapalok.github.io/grid__template__khrapal/
кст, а почему если я открываю шаблон с компьютера через гитхаб, то все
отображается корректно, когда открываю с ноутбука, то отображается слишком
большим все. при то что разрешение стоит 100%.
а когда открываю шаблон через редактор gulp watch --dev, то и с компа и с
ноута отображается все корректно?

вс, 23 окт. 2022 г. в 17:04, Артём Храпаль ***@***.***>:

**Comment by Alecto** [comment]
2 - не исправлено

![image](https://user-images.githubusercontent.com/8464662/197398065-8afa35f1-d15b-43ed-9209-7ca5ead20f3f.png)
